// <auto-generated />
using System;
using AlertService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlertService.Infrastructure.Migrations
{
    [DbContext(typeof(AlertServiceDbContext))]
    partial class AlertServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlertService.Domain.Entities.StoredAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlertData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CoinMintAddress")
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlertType")
                        .HasDatabaseName("ix_alerts_type");

                    b.HasIndex("CoinMintAddress")
                        .HasDatabaseName("ix_alerts_coin_mint_address")
                        .HasFilter("\"CoinMintAddress\" IS NOT NULL");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_alerts_created_at");

                    b.ToTable("alerts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
