// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TokenMetrics.Infrastructure.Data;

#nullable disable

namespace TokenMetrics.Infrastructure.Migrations
{
    [DbContext(typeof(TokenMetricsDbContext))]
    [Migration("20251110145521_AddAuthorIdToMentions")]
    partial class AddAuthorIdToMentions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CienceTerminal.Contracts.Models.CaMentionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CaAddress")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)");

                    b.Property<int>("Followers")
                        .HasColumnType("integer");

                    b.Property<bool>("IsQuote")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReply")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRetweet")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TweetId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CaAddress", "Timestamp")
                        .HasDatabaseName("ix_ca_mention_records_ca_timestamp");

                    b.HasIndex("TweetId", "CaAddress", "AuthorId")
                        .IsUnique()
                        .HasDatabaseName("ix_ca_mention_records_tweet_ca_author_unique");

                    b.ToTable("ca_mention_records", (string)null);
                });

            modelBuilder.Entity("TokenMetrics.Domain.Entities.CaAggregate", b =>
                {
                    b.Property<string>("CaAddress")
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)");

                    b.Property<string>("EmaValuesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("EnteredTop25At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastCalculated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastMentioned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("MentionCount1h")
                        .HasColumnType("double precision");

                    b.Property<double>("MentionCount24h")
                        .HasColumnType("double precision");

                    b.Property<double>("MentionCount5m")
                        .HasColumnType("double precision");

                    b.Property<double>("MentionCount6h")
                        .HasColumnType("double precision");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer");

                    b.Property<double>("TrendScore")
                        .HasColumnType("double precision");

                    b.HasKey("CaAddress");

                    b.HasIndex("Rank")
                        .HasDatabaseName("ix_ca_aggregates_rank")
                        .HasFilter("\"Rank\" IS NOT NULL");

                    b.HasIndex("TrendScore")
                        .IsDescending()
                        .HasDatabaseName("ix_ca_aggregates_trend_score");

                    b.ToTable("ca_aggregates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
