// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TokenMetrics.Infrastructure.Data;

#nullable disable

namespace TokenMetrics.Infrastructure.Migrations
{
    [DbContext(typeof(TokenMetricsDbContext))]
    [Migration("20251113140004_AddMentionAggregatesAndCoins")]
    partial class AddMentionAggregatesAndCoins
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CienceTerminal.Contracts.Models.CaMentionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CoinMintAddress")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)");

                    b.Property<int>("Followers")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOriginalPost")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsQuote")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReply")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRetweet")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TweetContent")
                        .HasMaxLength(30000)
                        .HasColumnType("character varying(30000)");

                    b.Property<string>("TweetId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TweetUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CoinMintAddress", "Timestamp")
                        .HasDatabaseName("ix_ca_mention_records_ca_timestamp");

                    b.HasIndex("TweetId", "CoinMintAddress", "AuthorId")
                        .IsUnique()
                        .HasDatabaseName("ix_ca_mention_records_tweet_ca_author_unique");

                    b.ToTable("ca_mention_records", (string)null);
                });

            modelBuilder.Entity("TokenMetrics.Domain.Entities.CaAggregate", b =>
                {
                    b.Property<string>("CaAddress")
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)");

                    b.Property<string>("EmaValuesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("EnteredTop25At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastCalculated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastMentioned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("MentionCount1h")
                        .HasColumnType("double precision");

                    b.Property<double>("MentionCount24h")
                        .HasColumnType("double precision");

                    b.Property<double>("MentionCount5m")
                        .HasColumnType("double precision");

                    b.Property<double>("MentionCount6h")
                        .HasColumnType("double precision");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer");

                    b.Property<double>("TrendScore")
                        .HasColumnType("double precision");

                    b.HasKey("CaAddress");

                    b.HasIndex("Rank")
                        .HasDatabaseName("ix_ca_aggregates_rank")
                        .HasFilter("\"Rank\" IS NOT NULL");

                    b.HasIndex("TrendScore")
                        .IsDescending()
                        .HasDatabaseName("ix_ca_aggregates_trend_score");

                    b.ToTable("ca_aggregates", (string)null);
                });

            modelBuilder.Entity("TokenMetrics.Domain.Entities.Coin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("CoinImage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("CoinImage");

                    b.Property<string>("CoinMintAddress")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasColumnName("CoinMintAddress");

                    b.Property<string>("CoinSymbol")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CoinSymbol");

                    b.Property<DateTime?>("FirstPoolCreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("FirstPoolCreatedAt");

                    b.Property<int?>("HolderCount")
                        .HasColumnType("integer")
                        .HasColumnName("HolderCount");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsBlacklisted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsBlacklisted");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamptz")
                        .HasColumnName("LastUpdated");

                    b.Property<decimal?>("Liquidity")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("Liquidity");

                    b.Property<decimal?>("MarketCap")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("MarketCap");

                    b.Property<int>("MentionCount24h")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("MentionCount24h");

                    b.Property<decimal?>("TopHoldersPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("TopHoldersPercentage");

                    b.Property<decimal?>("Volume24h")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("Volume24h");

                    b.HasKey("Id");

                    b.HasIndex("CoinMintAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_coins_mint_address");

                    b.HasIndex("LastUpdated")
                        .HasDatabaseName("ix_coins_last_updated");

                    b.HasIndex("MentionCount24h")
                        .IsDescending()
                        .HasDatabaseName("ix_coins_mention_count")
                        .HasFilter("\"IsActive\" = true");

                    b.ToTable("coins", (string)null);
                });

            modelBuilder.Entity("TokenMetrics.Domain.Entities.MentionAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("CoinMintAddress")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasColumnName("CoinMintAddress");

                    b.Property<DateTime>("LastCalculated")
                        .HasColumnType("timestamptz")
                        .HasColumnName("LastCalculated");

                    b.Property<DateTime>("LastMentioned")
                        .HasColumnType("timestamptz")
                        .HasColumnName("LastMentioned");

                    b.Property<double>("MentionCount1h")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("MentionCount1h");

                    b.Property<double>("MentionCount24h")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("MentionCount24h");

                    b.Property<double>("MentionCount5m")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("MentionCount5m");

                    b.Property<double>("MentionCount6h")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("MentionCount6h");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("Rank");

                    b.Property<double>("TrendingScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("TrendingScore");

                    b.HasKey("Id");

                    b.HasIndex("CoinMintAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_mention_aggregates_coin_address");

                    b.HasIndex("Rank")
                        .HasDatabaseName("ix_mention_aggregates_rank")
                        .HasFilter("\"Rank\" IS NOT NULL");

                    b.HasIndex("TrendingScore")
                        .IsDescending()
                        .HasDatabaseName("ix_mention_aggregates_trending_score");

                    b.ToTable("mention_aggregates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
