// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TwitterScanner.Infrastructure.Data;

#nullable disable

namespace TwitterScanner.Infrastructure.Migrations
{
    [DbContext(typeof(MentionPersistenceDbContext))]
    [Migration("20251112155020_SyncPendingModelChanges")]
    partial class SyncPendingModelChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CienceTerminal.Contracts.Models.CaMentionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CoinMintAddress")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)");

                    b.Property<int>("Followers")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOriginalPost")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsQuote")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReply")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRetweet")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TweetContent")
                        .HasMaxLength(30000)
                        .HasColumnType("character varying(30000)");

                    b.Property<string>("TweetId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TweetUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CoinMintAddress", "Timestamp")
                        .HasDatabaseName("ix_ca_mention_records_ca_timestamp");

                    b.HasIndex("TweetId", "CoinMintAddress", "AuthorId")
                        .IsUnique()
                        .HasDatabaseName("ix_ca_mention_records_tweet_ca_author_unique");

                    b.ToTable("ca_mention_records", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
